name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 
      - name: Install Lightsail Control Plugin
        run: |
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" /usr/local/bin/
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Push Image to Lightsail
        run: |
          aws lightsail push-container-image \
            --service-name my-lightsail-service \
            --label flask-app \
            --image my-app:latest

      - name: Deploy New Version
        run: |
          # 1. En son pushlanan imajı al
          IMAGE_NAME=$(aws lightsail get-container-images --service-name my-lightsail-service | jq -r '.containerImages[0].image')
          
          # 2. Sadece imaj ismini JSON'a bas
          jq --arg img "$IMAGE_NAME" '.app.image = $img' infra/container-config.json > deploy.json
          
          # 3. Deployment'ı yap
          aws lightsail create-container-service-deployment \
            --service-name my-lightsail-service \
            --containers file://deploy.json \
            --public-endpoint '{"containerName":"app","containerPort":5000,"healthCheck":{"path":"/health"}}'